"""
End-to-end demo of the autonomous mastering agent.

Runs two scenarios against the synthetic test mix generated by
make_synthetic_mix.py:

  1. Genre-profile mode  : no reference track, agent infers a target curve
                            by matching the mix against the genre profile bank.
  2. Reference-match mode: agent computes a differential against
                            reference_master.wav and masters toward it.

Uses GeminiDecisionEngine by default (which transparently falls back to the
deterministic RuleBasedDecisionEngine if no GEMINI_API_KEY/GOOGLE_API_KEY is
set in the environment -- the pipeline never stalls waiting on an LLM).

Usage:
    python run_demo.py
"""
import os
import subprocess
import sys

from mastering_agent import decision, orchestrator


def ensure_test_audio():
    if not (os.path.exists("synth_mix.wav") and os.path.exists("reference_master.wav")):
        print("Generating synthetic test audio...")
        subprocess.run([sys.executable, "make_synthetic_mix.py"], check=True)


def main():
    ensure_test_audio()
    engine = decision.GeminiDecisionEngine()  # auto-falls-back to rule-based if no API key

    print("\n" + "=" * 70)
    print("SCENARIO 1: Genre-profiling mode (no reference track)")
    print("=" * 70)
    result_a = orchestrator.run_mastering_loop(
        input_path="synth_mix.wav",
        output_path="output/master_genre_profile.wav",
        reference_path=None,
        engine=engine,
        max_iterations=6,
    )
    orchestrator.save_report(result_a, "output/report_genre_profile.json")
    _print_summary("Genre-profiling", result_a)

    print("\n" + "=" * 70)
    print("SCENARIO 2: Reference-matching mode")
    print("=" * 70)
    engine2 = decision.GeminiDecisionEngine()
    result_b = orchestrator.run_mastering_loop(
        input_path="synth_mix.wav",
        output_path="output/master_reference_matched.wav",
        reference_path="reference_master.wav",
        engine=engine2,
        max_iterations=6,
    )
    orchestrator.save_report(result_b, "output/report_reference_matched.json")
    _print_summary("Reference-matching", result_b)

    print("\nAll outputs written to ./output/")


def _print_summary(label, result):
    f = result.final_features
    print(f"\n--- {label} summary ---")
    print(f"Engine used      : {result.engine_used}")
    print(f"Output file      : {result.output_path}")
    print(f"Final LUFS       : {f['lufs_integrated']:.2f}")
    print(f"Final True Peak  : {f['true_peak_dbtp']:.2f} dBTP")
    print(f"Final Crest      : {f['crest_factor_db']:.2f} dB  (hard floor = {decision.MIN_CREST_FACTOR_DB} dB)")
    print(f"Final Stereo W   : {f['stereo_width']:.4f}")
    if result.warnings:
        print("Warnings:")
        for w in result.warnings:
            print(f"  - {w}")
    else:
        print("Warnings: none")


if __name__ == "__main__":
    main()
